spring:
  application:
    name: flight-tracking
  redis:
    host: redis
    port: 6379

server:
  port: 8081

camel:
  component:
    kafka:
      brokers: localhost:29092
      inputTopic: flights.live.status
#      dlqTopic: flights.dlq